# Generated by Django 5.1.1 on 2024-09-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
